# Generated by Django 4.0.1 on 2022-02-21 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_history_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='user',
        ),
    ]
